"""
Hand-written descriptions of preset fields whose source code has no comment.

Keys are "ClassName.field". They feed the JSON Schema (schemas/ppg-preset.schema.json) and the field
reference (docs/preset-fields.md); keep them short, give the meaning, the unit and typical values.
"""

FIELD_DOCS = {
    # --- Identity -------------------------------------------------------------------------------------
    "BotanicalSpeciesPreset.scientific_name": "Binomial name, e.g. 'Quercus robur' (shown in the UI and object names).",
    "BotanicalSpeciesPreset.common_name": "Vernacular name(s), e.g. 'English Oak (roble)'.",
    "BotanicalSpeciesPreset.family": "Botanical family, e.g. 'Fagaceae'.",
    "BotanicalSpeciesPreset.biome": "Biome or habitat, e.g. 'Temperate Deciduous'.",
    "BotanicalSpeciesPreset.notes": "Free text: distinctive features, sources of the values.",
    "BotanicalSpeciesPreset.deciduous": "True if the tree sheds its leaves seasonally (enables autumn colour).",
    "SucculentPreset.scientific_name": "Binomial name, e.g. 'Carnegiea gigantea'.",
    "SucculentPreset.common_name": "Vernacular name(s).",
    "SucculentPreset.family": "Botanical family, e.g. 'Cactaceae', 'Asparagaceae'.",
    "SucculentPreset.biome": "Native range or habitat.",
    "SucculentPreset.form": "Growth form; must match the envelope's growth_form ('Cactus' or 'Rosette').",
    "SucculentPreset.notes": "Free text: distinctive features, sources of the values.",
    "FlowerPreset.scientific_name": "Binomial name, e.g. 'Rosa canina'.",
    "FlowerPreset.common_name": "Vernacular name(s).",
    "FlowerPreset.family": "Botanical family, e.g. 'Rosaceae'.",
    "FlowerPreset.formula": "Floral formula (K calyx, C corolla, P tepals, A stamens, G carpels), e.g. 'K5 C5 A∞ G∞'.",
    "FlowerPreset.notes": "Free text: distinctive features, sources of the values.",
    "VinePreset.scientific_name": "Binomial name, e.g. 'Ipomoea purpurea'.",
    "VinePreset.common_name": "Vernacular name(s).",
    "VinePreset.family": "Botanical family, e.g. 'Convolvulaceae', 'Cucurbitaceae'.",
    "VinePreset.biome": "Native range or habitat.",
    "VinePreset.notes": "Free text: distinctive features, sources of the values.",
    "FruitPreset.scientific_name": "Binomial name of the plant bearing the fruit, e.g. 'Malus domestica'.",
    "FruitPreset.common_name": "Vernacular name(s) of the fruit.",
    "FruitPreset.family": "Botanical family, e.g. 'Rosaceae'.",
    "FruitPreset.notes": "Free text: distinctive features, sources of the values.",
    "FruitProfile.kind": "Fruit type (Spjut 1994): Berry, Drupe, Pome, Hesperidium (citrus), Balausta (pomegranate), Pepo (cucurbits), Pod. Informative; the shape comes from the other fields.",
    "FruitProfile.crown_position": "Where the persistent calyx sits: 'Distal' (blossom end: apple, pomegranate) or 'Proximal' (a star on the stalk end: tomato, aubergine).",
    "FruitProfile.crown_color": "Colour of the calyx lobes (sRGB 0..1).",
    "FruitProfile.stalk_color": "Colour of the stalk, peduncle and pedicels.",
    "FruitProfile.color": "Ground colour of the skin (sRGB 0..1).",
    "FruitProfile.blush_color": "Over-colour on the sun side (sRGB 0..1).",
    "FruitProfile.stripe_color": "Colour of the streaks / stripes.",
    "FruitProfile.dot_color": "Colour of the lenticels, oil glands or speckles.",
    "FruitProfile.stalk_radius_mm": "Stalk radius, mm; for bunches, the radius of the peduncle and rachis.",
    "FruitProfile.gloss": "Skin gloss, 0 matt .. 1 glossy (cherries, tomatoes).",
    "VegetablePreset.scientific_name": "Binomial name, e.g. 'Daucus carota subsp. sativus'.",
    "VegetablePreset.common_name": "Vernacular name(s).",
    "VegetablePreset.family": "Botanical family, e.g. 'Apiaceae', 'Brassicaceae'.",
    "VegetablePreset.notes": "Free text: distinctive features, sources of the values.",
    "VegetableProfile.organ": "Storage or harvested organ: 'Taproot' (carrot, radish, beet, turnip), 'Tubers' (potato), 'Tuberous roots' (sweet potato, cassava: fasciculate storage roots), 'Head' (cauliflower, broccoli, Romanesco) or 'None' (leaves only).",
    "VegetableProfile.stem_radius_mm": "Radius of the stems at the base, mm.",
    "VegetableProfile.root_length_cm": "Length of the swollen root from the crown to the start of the tail, cm.",
    "VegetableProfile.root_diameter_cm": "Largest diameter of the storage root, cm.",
    "VegetableProfile.tail_cm": "Length of the thin root below the swollen part, cm.",
    "VegetableProfile.root_color": "Skin colour of the root below the soil (sRGB 0..1).",
    "VegetableProfile.tuber_count": "Number of tubers per plant.",
    "VegetableProfile.tuber_length_cm": "Tuber length from the heel (stolon end) to the rose end, cm.",
    "VegetableProfile.tuber_diameter_cm": "Largest tuber diameter, cm.",
    "VegetableProfile.tuber_depth_cm": "Depth of the tubers below the soil surface, cm.",
    "VegetableProfile.stolon_length_cm": "Length of the stolons that carry the tubers, cm.",
    "VegetableProfile.eyes": "Number of eyes (buds) per tuber, on a ~2/5 spiral crowded toward the rose end.",
    "VegetableProfile.eye_depth": "Depth of the eye dimples relative to the radius.",
    "VegetableProfile.tuber_color": "Tuber skin colour (sRGB 0..1).",
    "VegetableProfile.tuber_dots": "Density of the lenticel dots on the tuber skin.",
    "VegetableProfile.head_type": "'Curd' (cauliflower: packed meristem domes), 'Buds' (broccoli: flower-bud clusters on branches) or 'Cones' (Romanesco: self-similar cones).",
    "VegetableProfile.head_diameter_cm": "Diameter of the head, cm.",
    "VegetableProfile.head_color": "Colour of the curd, buds or cones (sRGB 0..1).",
    "VegetableProfile.branch_color": "Colour of the head branches and of its base (sRGB 0..1).",
    "OrchidPreset.scientific_name": "Binomial name, e.g. 'Phalaenopsis amabilis'.",
    "OrchidPreset.common_name": "Vernacular name(s).",
    "OrchidPreset.family": "Botanical family ('Orchidaceae').",
    "OrchidPreset.notes": "Free text: habit, distinctive features, sources of the values.",
    "OrchidProfile.stem_color": "Colour of stems, canes, pseudobulbs and rhizome (sRGB 0..1).",
    "OrchidProfile.sheath_color": "Colour of the papery sheaths, dry node rings and bracts (sRGB 0..1).",
    "OrchidProfile.leaf_length_cm": "Length of the largest (oldest) leaves, cm.",
    "OrchidProfile.leaf_width_cm": "Width of the leaves at their widest point, cm.",
    "OrchidProfile.leaf_twist_deg": "Random twist along the leaf, degrees.",
    "OrchidProfile.leaf_color": "Leaf colour (sRGB 0..1).",
    "OrchidProfile.root_length_cm": "Length of the aerial roots, cm.",
    "OrchidProfile.inflorescences": "Number of inflorescences (spikes, racemes, panicles or node clusters).",
    "OrchidProfile.spike_radius_mm": "Radius of the inflorescence axis at its base, mm.",
    "OrchidProfile.spike_color": "Colour of peduncle, rachis, pedicels and ovaries (sRGB 0..1).",
    "OrchidProfile.sepal_width_cm": "Width of the dorsal sepal, cm.",
    "OrchidProfile.sepal_widest": "Position of the widest point of the sepals, 0 base .. 1 tip.",
    "OrchidProfile.sepal_apex_deg": "Angle at the sepal apex, degrees (small = acuminate, 180 = rounded).",
    "OrchidProfile.sepal_cup": "Transverse concavity of the sepals (negative: margins recurved).",
    "OrchidProfile.sepal_twist_deg": "Twist along the sepals, degrees (Prosthechea: twisted, hanging).",
    "OrchidProfile.sepal_wave": "Wavy sepal margins, 0..1.",
    "OrchidProfile.petal_length_cm": "Length of the lateral petals, cm.",
    "OrchidProfile.petal_width_cm": "Width of the lateral petals, cm.",
    "OrchidProfile.petal_widest": "Position of the widest point of the petals, 0 base .. 1 tip.",
    "OrchidProfile.petal_apex_deg": "Angle at the petal apex, degrees (small = acuminate, 180 = rounded).",
    "OrchidProfile.petal_cup": "Transverse concavity of the petals (negative: margins recurved).",
    "OrchidProfile.petal_reflex_deg": "Bending back along the petals, degrees.",
    "OrchidProfile.petal_twist_deg": "Twist along the petals, degrees (Paphiopedilum, Prosthechea).",
    "OrchidProfile.lip_widest": "Position of the widest point of the mid lobe (or entire lip), 0 base .. 1 apex.",
    "OrchidProfile.lip_apex_deg": "Angle at the lip apex, degrees (small = pointed, 180 = rounded).",
    "OrchidProfile.column_width_mm": "Column (gynostemium) diameter, mm.",
    "OrchidProfile.petal_color": "Lateral petal colour (sRGB 0..1).",
    "OrchidProfile.lip_color": "Labellum colour (sRGB 0..1).",
    "OrchidProfile.lip_throat_color": "Colour of the lip base / throat (inside a tube) (sRGB 0..1).",
    "OrchidProfile.callus_color": "Colour of the callus, ridges and cirrhi (sRGB 0..1).",
    "OrchidProfile.column_color": "Column colour (sRGB 0..1).",
    "OrchidProfile.anther_color": "Colour of the anther cap and staminode (sRGB 0..1).",
    "OrchidProfile.pattern_color": "Colour of spots, bars and venation (anthocyanin) (sRGB 0..1).",
    "OrchidProfile.lip_spots": "Spots on the lip and callus, 0..1.",
    "OrchidProfile.lip_veins": "Coloured venation on the lip, 0..1.",
    "GrassPreset.scientific_name": "Binomial name, e.g. 'Zea mays'.",
    "GrassPreset.common_name": "Vernacular name(s).",
    "GrassPreset.family": "Botanical family ('Poaceae').",
    "GrassPreset.notes": "Free text: distinctive features, sources of the values.",
    "GrassProfile.tillers": "Shoots of the clump: the main shoot plus its tillers (maize 1, wheat 3-6, rice 8-15, lawn tufts 20-40).",
    "GrassProfile.clump_radius_cm": "Radius of the base of the clump, cm.",
    "GrassProfile.culm_radius_mm": "Culm (stem) radius at the base, mm.",
    "GrassProfile.culm_color": "Culm and sheath colour (sRGB 0..1).",
    "GrassProfile.leaf_length_cm": "Length of the longest blade (from the ligule), cm.",
    "GrassProfile.leaf_width_cm": "Width of the widest blade, cm.",
    "GrassProfile.leaf_color": "Blade colour (sRGB 0..1).",
    "GrassProfile.midrib_color": "Colour of the midrib (pale in maize and sorghum).",
    "GrassProfile.head": "Inflorescence: 'Spike' (wheat, barley), 'Panicle' (oats, rice, sorghum), 'Plume' (pampas and fountain grass), 'One-sided' (Bouteloua), 'Maize' (tassel and ears) or 'None' (leafy tufts, lawn).",
    "GrassProfile.head_length_cm": "Length of the spike, panicle, plume, one-sided spikes or tassel, cm.",
    "GrassProfile.head_width_cm": "Width of a panicle or plume, cm.",
    "GrassProfile.spikelets": "Spikelets per head (spikes, panicles) or hairs of a plume.",
    "GrassProfile.spikelet_mm": "Spikelet length, mm.",
    "GrassProfile.head_color": "Colour of the spikelets (sRGB 0..1).",
    "GrassProfile.awn_color": "Colour of the awns and plume hairs.",
    "GrassProfile.ears": "Maize ears per plant (the upper one largest).",
    "GrassProfile.ear_length_cm": "Maize ear (cob) length, cm.",
    "GrassProfile.ear_diameter_cm": "Maize ear diameter, cm.",
    "GrassProfile.kernel_rows": "Rows of kernels around the cob (even, 8-24).",
    "GrassProfile.silk_cm": "Length of the silks out of the ear tip, cm.",
    "GrassProfile.kernel_color": "Kernel colour (sRGB 0..1).",
    "GrassProfile.silk_color": "Silk colour.",
    "GrassProfile.node_color": "Colour of the node ring and root band (sRGB 0..1).",
    "GrassProfile.crown_roots": "Number of crown (nodal) roots.",
    "GrassProfile.root_length_cm": "Crown root length shown, cm.",
    # --- Vines ------------------------------------------------------------------------------------------
    "VineProfile.mode": "How the stem uses its guide path: 'Twining' coils around it (the guide is the support), 'Tendril' follows it and grasps it with tendrils, 'Clinging' is pressed to it by rootlets (walls), 'Trailing' creeps along it on the ground.",
    "VineProfile.chirality": "Handedness of the twining helix: 'Right' = counter-clockwise seen from above (about 90 % of twiners: Ipomoea, Phaseolus, Wisteria sinensis); 'Left' = clockwise (Humulus, Lonicera).",
    "VineProfile.branch_length_cm": "Length of a lateral shoot from an old node, cm (shorter near the apex).",
    "VineProfile.tendril_length_cm": "Tendril length when straight, cm (Pisum 5-10, Cucumis 15-25, Vitis 10-20).",
    "VineProfile.tendril_radius_mm": "Tendril thickness (radius), mm.",
    "VineProfile.rootlet_length_cm": "Length of the nodal / adventitious rootlets, cm.",
    # --- Allometry --------------------------------------------------------------------------------------
    "AllometricProfile.dbh_max_m": "Largest stem diameter at breast height (1.3 m) for the species, metres.",
    "AllometricProfile.dbh_default_m": "Stem diameter at 1.3 m used by default; sets height and crown through the allometric laws. Mature broadleaves 0.4-1.0 m.",
    "AllometricProfile.crown_radius_d": "Exponent d of the crown radius law CR = c * (DBH_cm)^d (typically 0.45-0.65).",
    # --- Architecture -----------------------------------------------------------------------------------
    "ArchitectureProfile.model": "Hallé-Oldeman architectural model: Rauh (rhythmic orthotropic, oaks, pines), Massart (horizontal tiers, firs), Troll (plagiotropic axes erect at the tip, beech, elm), Attims (continuous branching, eucalyptus), Corner (unbranched with apical crown, palms).",
    "ArchitectureProfile.phyllotaxis": "Arrangement of leaves and branches along a shoot: Spiral (alternate), Decussate (opposite pairs, maples, ash), Distichous (two ranks), Whorled.",
    "ArchitectureProfile.branch_angle_std_deg": "Standard deviation of the scaffold branch angle, degrees (natural irregularity, 4-10).",
    "ArchitectureProfile.divergence_angle_deg": "Angle between successive lateral organs around the axis, degrees: 137.5 spiral (golden angle), 180 distichous, 90 decussate.",
    "ArchitectureProfile.internode_length_base_m": "Length of a growth unit on the main axes, metres (0.2-0.8 for trees).",
    "ArchitectureProfile.crookedness": "Tortuosity of the axes, 0 straight .. 0.6 very winding (olive, old oaks).",
    "ArchitectureProfile.crown_widest_position": "Relative height (0 bottom .. 1 top of the crown) where the crown is widest: ~0.2 conical, 0.4-0.5 rounded, 0.7 vase.",
    "ArchitectureProfile.crown_fullness": "Shape of the beta crown envelope: < 1 columnar / flat sides, 1.5 rounded, > 2 peaked.",
    # --- Leaf ---------------------------------------------------------------------------------------------
    "LeafMorphologyProfile.archetype": "Leaf-shape template (Ellis et al. 2009 vocabulary); individual descriptors below refine it.",
    "LeafMorphologyProfile.margin_type": "Leaf margin: Entire, Serrate, Dentate, Crenate, Doubly serrate, ... (sets tooth shape).",
    "LeafMorphologyProfile.petiole_radius_mm": "Petiole radius, millimetres.",
    "LeafMorphologyProfile.transverse_curl": "Curl of the blade across its width, 0 flat .. 1 strongly folded along the midrib.",
    "LeafMorphologyProfile.longitudinal_droop": "Downward bending of the blade along its length, 0 straight .. 1 drooping.",
    "LeafMorphologyProfile.undulation_amplitude": "Waviness of the margin, 0 flat .. 0.5 strongly undulate.",
    "LeafMorphologyProfile.abaxial_color": "Colour of the lower leaf surface, sRGB 0..1 (usually paler than the upper).",
    "LeafMorphologyProfile.vein_color": "Colour of the veins, sRGB 0..1.",
    "LeafMorphologyProfile.autumn_color": "Senescent (autumn) leaf colour, sRGB 0..1.",
    "LeafMorphologyProfile.gloss": "Glossiness of the upper surface, 0 matt .. 1 waxy (Ficus, Magnolia).",
    # --- Venation -----------------------------------------------------------------------------------------
    "VenationProfile.pattern": "Secondary venation pattern (Ellis et al. 2009): craspedodromous (veins end in teeth), brochidodromous (looping), actinodromous (palmate), parallelodromous (monocots), ...",
    "VenationProfile.primary_radius_mm": "Half-width of the midrib in the leaf texture, millimetres.",
    "VenationProfile.secondary_radius_mm": "Half-width of secondary veins, millimetres.",
    "VenationProfile.tertiary_radius_mm": "Half-width of tertiary veins, millimetres.",
    # --- Bark ---------------------------------------------------------------------------------------------
    "BarkProfile.pattern": "Rhytidome type (Junikka 1994): Smooth, Fissured (furrowed ridges), Plated (scales/plates), Peeling (exfoliating patches), Lenticelled (horizontal lenticels), Fibrous (stringy strips), Annulated (leaf-scar rings).",
    "BarkProfile.roughness": "Surface roughness of the bark material, 0 glossy .. 1 rough (bark is typically 0.75-0.95).",
    "BarkProfile.onset_radius_cm": "Axis radius (cm) where the mature bark pattern replaces the smooth young periderm; fissures widen beyond it.",
    # --- Roots --------------------------------------------------------------------------------------------
    "RootProfile.system": "Root system type (Köstler et al. 1968; Cannon 1949): Taproot, Heart, Plate (shallow), Buttress, Stilt (prop roots), Fibrous (fasciculate), Tuberous (napiform storage taproot), Tuberous cluster (fasciculate storage roots).",
    "RootProfile.tortuosity": "Winding of the roots through the soil, 0 straight .. 1 very tortuous.",
    "RootProfile.fibrous_radius_m": "Radius of the fine fibrous roots, metres.",
    "RootProfile.tuber_radius_m": "Radius of a storage tuber (Tuberous system), metres.",
    # --- Cactus -------------------------------------------------------------------------------------------
    "CactusProfile.habit": "Body plan: Columnar (saguaro, organ pipe), Barrel, Globose, Cladode (Opuntia pads).",
    "CactusProfile.arrangement": "Areole layout: Ribs (on rib crests) or Tubercles (spiral lattice of podaria, Mammillaria).",
    "CactusProfile.diameter_m": "Stem diameter, metres (main trunk for branched species).",
    "CactusProfile.rib_twist_deg_per_m": "Helical twist of the ribs, degrees per metre of height (0 straight).",
    "CactusProfile.areole_spacing_cm": "Distance between neighbouring areoles along a rib or in the lattice, cm.",
    "CactusProfile.radial_length_cm": "Length of the radial spines, cm.",
    "CactusProfile.central_spines": "Number of central spines per areole.",
    "CactusProfile.central_length_cm": "Length of the central spines, cm.",
    "CactusProfile.spine_thickness_mm": "Spine base diameter, mm.",
    "CactusProfile.spine_jitter": "Random variation of spine direction and length, 0 regular .. 1 messy.",
    "CactusProfile.arm_height_max": "Highest arm insertion, as a fraction of the stem height.",
    "CactusProfile.arm_radius_ratio": "Arm radius relative to the trunk radius.",
    "CactusProfile.arm_branching": "Mean number of secondary arms per arm (dense candelabra crowns).",
    "CactusProfile.offset_scale": "Size of basal offsets (pups) relative to the mother stem.",
    "CactusProfile.pad_width_ratio": "Cladode width / length (Opuntia ~0.6).",
    "CactusProfile.pad_thickness_ratio": "Cladode thickness / length (Opuntia ~0.06).",
    "CactusProfile.pad_levels": "Number of cladode generations in the chain (plant age / height).",
    "CactusProfile.groove_color": "Colour at the bottom of the grooves between ribs, sRGB 0..1.",
    "CactusProfile.spine_color": "Spine colour at the base, sRGB 0..1.",
    "CactusProfile.spine_tip_color": "Spine colour at the tip, sRGB 0..1.",
    "CactusProfile.wool_color": "Colour of areolar and apical wool, sRGB 0..1.",
    "CactusProfile.scaling_color": "Colour of early epidermal browning ('scaling', tan to red-orange), sRGB 0..1.",
    "CactusProfile.barking_color": "Colour of old epidermal bark ('barking', dark brown or grey), sRGB 0..1.",
    "CactusProfile.scar_color": "Colour of corky scars, sRGB 0..1.",
    "CactusProfile.root_count": "Number of main lateral roots.",
    "CactusProfile.taproot_share": "Fraction of the root collar taken by a taproot (0 none .. 0.8 dominant taproot).",
    "CactusProfile.taproot_depth_m": "Taproot depth, metres.",
    "CactusProfile.tuber_length_cm": "Length of a napiform storage tuber (peyote), cm.",
    # --- Rosette ------------------------------------------------------------------------------------------
    "RosetteProfile.phyllotaxis": "Leaf arrangement: Spiral (golden angle, most rosettes) or Distichous (two ranks, Gasteria).",
    "RosetteProfile.leaf_count": "Number of living leaves in the rosette.",
    "RosetteProfile.stem_radius_m": "Stem radius under the rosette, metres.",
    "RosetteProfile.leaf_length_cm": "Length of the outermost mature leaves, cm.",
    "RosetteProfile.elevation_outer_deg": "Elevation of the oldest, outer leaves above horizontal, degrees.",
    "RosetteProfile.elevation_inner_deg": "Elevation of the youngest, central leaves, degrees (near 90 = erect spike).",
    "RosetteProfile.widest_position": "Position of the widest point along the leaf, 0 base .. 1 tip.",
    "RosetteProfile.base_angle_deg": "Angle enclosed by the leaf margins at the base, degrees.",
    "RosetteProfile.apex_angle_deg": "Angle enclosed by the leaf margins at the apex, degrees (small = acuminate).",
    "RosetteProfile.base_curvature": "Curvature of the basal margin, -1 concave .. +1 convex.",
    "RosetteProfile.apex_curvature": "Curvature of the apical margin, -1 concave (acuminate) .. +1 rounded.",
    "RosetteProfile.dead_color": "Colour of withered leaves, sRGB 0..1.",
    "RosetteProfile.terminal_spine_cm": "Length of the terminal leaf spine (Agave), cm; 0 = none.",
    "RosetteProfile.teeth_size_cm": "Size of the marginal teeth, cm; 0 = none.",
    "RosetteProfile.teeth_hook": "How much marginal teeth curve toward the leaf tip, 0 straight .. 1 hooked.",
    "RosetteProfile.offsets": "Number of offsets (pups) around the main rosette.",
    "RosetteProfile.offset_scale": "Size of the offsets relative to the main rosette.",
    "RosetteProfile.leaf_color": "Base leaf colour, sRGB 0..1.",
    "RosetteProfile.blush_color": "Anthocyanin blush colour of margins and tips, sRGB 0..1.",
    "RosetteProfile.armature_color": "Colour of spines and teeth, sRGB 0..1.",
    "RosetteProfile.root_system": "Root system type (rosettes: usually Fibrous).",
    "RosetteProfile.root_count": "Number of roots.",
    "RosetteProfile.root_depth_m": "Rooting depth holding 90% of the roots, metres.",
    "RosetteProfile.root_radius_mm": "Root radius at the collar, mm.",
    # --- Flower -------------------------------------------------------------------------------------------
    "FlowerProfile.widest_position": "Position of the widest point of the petal, 0 base .. 1 tip.",
    "FlowerProfile.base_angle_deg": "Angle enclosed by the petal margins at the base, degrees.",
    "FlowerProfile.apex_angle_deg": "Angle enclosed by the petal margins at the apex, degrees (180 = truncate).",
    "FlowerProfile.apex_curvature": "Curvature of the petal apex, -1 acuminate .. +1 rounded.",
    "FlowerProfile.fringe_count": "Number of teeth or fringe lobes at the petal apex.",
    "FlowerProfile.sepal_aspect": "Sepal length / width.",
    "FlowerProfile.sepal_opening_deg": "Elevation of the sepals above the floral plane, degrees (negative = reflexed).",
    "FlowerProfile.stamen_length_ratio": "Stamen length relative to the petal length.",
    "FlowerProfile.stamen_spread_deg": "Outward tilt of the stamens from the floral axis, degrees.",
    "FlowerProfile.anther_size_mm": "Anther length, mm.",
    "FlowerProfile.style_length_ratio": "Style length relative to the petal length (0 = no visible pistil).",
    "FlowerProfile.stigma_size_mm": "Size of each stigma lobe, mm.",
    "FlowerProfile.receptacle_radius_cm": "Radius of the receptacle (floral base), cm.",
    "FlowerProfile.disc_florets": "Number of disc florets in a capitulum (sunflower ~1000).",
    "FlowerProfile.disc_radius_cm": "Radius of the capitulum disc, cm.",
    "FlowerProfile.disc_dome": "Doming of the disc, 0 flat .. 1 hemispherical.",
    "FlowerProfile.involucre_bracts": "Number of involucral bracts (phyllaries) under a capitulum.",
    "FlowerProfile.tip_color": "Petal colour at the tip (gradient from petal_color), sRGB 0..1.",
    "FlowerProfile.eye_color": "Colour of the contrasting zone at the petal base (eye) and of nectar guides, sRGB 0..1.",
    "FlowerProfile.guide_contrast": "Strength of the nectar guides, 0 none .. 1 strong.",
    "FlowerProfile.spot_color": "Colour of petal spots (Lilium), sRGB 0..1.",
    "FlowerProfile.outer_tint": "Strength of the outer_color tint on outer tepals (sepaloid gradient), 0..1.",
    "FlowerProfile.sepal_color": "Colour of sepals, bracts and the floral cup, sRGB 0..1.",
    "FlowerProfile.stamen_color": "Filament colour, sRGB 0..1.",
    "FlowerProfile.anther_color": "Anther (pollen) colour, sRGB 0..1.",
    "FlowerProfile.pistil_color": "Style, stigma and receptacle colour, sRGB 0..1.",
    "FlowerProfile.disc_color": "Colour of mature disc florets (capitulum rim), sRGB 0..1.",
    "FlowerProfile.disc_center_color": "Colour of the young central disc florets, sRGB 0..1.",
    "FlowerProfile.translucency": "Light transmission of the petals, 0 opaque .. 1 thin and translucent.",
    "InflorescenceProfile.kind": "Inflorescence type: Solitary, Raceme, Spike, Catkin, Umbel, Corymb, Panicle (Weberling 1989).",
    "InflorescenceProfile.flower_count": "Number of flowers (per panicle branch counts are derived).",
    "InflorescenceProfile.pedicel_cm": "Length of the individual flower stalks, cm (0 for spikes and catkins).",
    "InflorescenceProfile.divergence_deg": "Angle between successive flowers around the rachis, degrees (137.5 spiral).",
    "InflorescenceProfile.branch_length_ratio": "Length of panicle branches relative to the rachis.",
    "InflorescenceProfile.branch_angle_deg": "Angle of panicle branches from the rachis, degrees.",
    "InflorescenceProfile.stem_radius_mm": "Radius of the peduncle at its base, mm.",
    "InflorescenceProfile.stem_color": "Colour of peduncle, rachis and pedicels, sRGB 0..1.",
    "InflorescenceProfile.site_mode": "Where inflorescences go on a plant: Terminal (shoot tips, rosette centre) or Axillary (along shoots, leaf axils).",
}
