"""
Botanical Species Database with Empirical Traits and Plant Ontology Grounding.
Synthesizes measurements from:
- TALLO Database (Jucker et al. 2022) for allometric height, DBH, and crown scaling.
- UC Berkeley Botanical Garden 122 Species Dataset (Matos, Boakye, Antonio, Carlos, Chu, Duarte et al. 2025)
  for venation density (VLA), leaf thickness, and laminar traits.
- LeavesBank Dataset (Yildirim et al. 2024) for leaf contour boundaries.
- Plant Ontology (Planteome / plantontology.org) for anatomical entity anchoring.
- Hallé-Oldeman Architectural Classification.
- Gielis Superformula (2003) for fluted trunk buttressing.
"""

from .allometry import AllometricProfile
from .architecture import ArchitectureProfile, HalleOldemanModel, PhyllotaxisType
from .leaf_morphology import LeafMorphologyProfile, LeafArchetype, MarginType
from .leaf_venation import VenationProfile, VenationPattern
from .biomechanics import BiomechanicalProfile
from .species_preset import BotanicalSpeciesPreset


# -----------------------------------------------------------------------------
# Curated Empirical Botanical Species Catalog
# -----------------------------------------------------------------------------
SPECIES_CATALOG: dict[str, BotanicalSpeciesPreset] = {
    "quercus_robur": BotanicalSpeciesPreset(
        scientific_name="Quercus robur",
        common_name="English Oak",
        family="Fagaceae",
        biome="Temperate Deciduous",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Massive broad crown, high mechanical wood density, deeply lobed leaves, craspedodromous venation.",
        allometry=AllometricProfile(
            dbh_min_m=0.05,
            dbh_max_m=1.80,
            dbh_default_m=0.55,
            height_a=1.92,
            height_b=0.56,
            height_max_m=34.0,
            crown_radius_c=0.55,
            crown_radius_d=0.58,
            crown_depth_ratio=0.62,
            pipe_exponent_delta=2.30,
            wood_density_g_cm3=0.71,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.RAUH,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=3,
            branch_angle_mean_deg=46.0,
            branch_angle_std_deg=7.5,
            apical_dominance=0.55,
            gravitropism=-0.18,
            internode_length_base_m=0.48,
            crookedness=0.18,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.LOBATE_PINNATE,
            margin_type=MarginType.ENTIRE,
            blade_length_cm=11.0,
            aspect_ratio=1.75,
            petiole_length_ratio=0.15,
            transverse_curl=0.22,
            longitudinal_droop=0.30,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.CRASPEDODROMOUS,
            vla_mm_per_mm2=7.4,
            secondary_vein_pairs=7,
            divergence_angle_deg=48.0,
            primary_radius_mm=0.92,
            secondary_radius_mm=0.32,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.71,
            youngs_modulus_gpa=12.5,
            leaf_mass_per_area_g_m2=95.0,
        )
    ),

    "quercus_agrifolia": BotanicalSpeciesPreset(
        scientific_name="Quercus agrifolia",
        common_name="Coast Live Oak",
        family="Fagaceae",
        biome="Mediterranean / California Chaparral",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Evergreen sclerophyllous oak, gnarled crooked branches, convex spiny-dentate leaves (from UC Berkeley dataset).",
        allometry=AllometricProfile(
            dbh_min_m=0.04,
            dbh_max_m=1.30,
            dbh_default_m=0.45,
            height_a=1.68,
            height_b=0.51,
            height_max_m=24.0,
            crown_radius_c=0.60,
            crown_radius_d=0.56,
            crown_depth_ratio=0.72,
            pipe_exponent_delta=2.25,
            wood_density_g_cm3=0.76,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.TROLL,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=3,
            branch_angle_mean_deg=54.0,
            branch_angle_std_deg=8.5,
            apical_dominance=0.35,
            gravitropism=-0.10,
            internode_length_base_m=0.40,
            crookedness=0.28,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.OVATE,
            margin_type=MarginType.DENTATE,
            blade_length_cm=5.5,
            aspect_ratio=1.40,
            petiole_length_ratio=0.20,
            teeth_count=14,
            tooth_height_ratio=0.06,
            transverse_curl=0.40,
            longitudinal_droop=0.18,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.CRASPEDODROMOUS,
            vla_mm_per_mm2=9.8,
            secondary_vein_pairs=6,
            divergence_angle_deg=50.0,
            primary_radius_mm=0.82,
            secondary_radius_mm=0.28,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.76,
            youngs_modulus_gpa=13.8,
            leaf_mass_per_area_g_m2=145.0,
        )
    ),

    "acer_palmatum": BotanicalSpeciesPreset(
        scientific_name="Acer palmatum",
        common_name="Japanese Maple",
        family="Sapindaceae",
        biome="Temperate Broadleaf",
        growth_habit="Sub-canopy Tree",
        po_growth_form="PO:0009006",
        notes="Palmate 5-lobed leaves with actinodromous primary venation, decussate opposite branching.",
        allometry=AllometricProfile(
            dbh_min_m=0.03,
            dbh_max_m=0.45,
            dbh_default_m=0.18,
            height_a=1.65,
            height_b=0.52,
            height_max_m=12.0,
            crown_radius_c=0.48,
            crown_radius_d=0.54,
            crown_depth_ratio=0.70,
            pipe_exponent_delta=2.20,
            wood_density_g_cm3=0.64,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.TROLL,
            phyllotaxis=PhyllotaxisType.DECUSSATE,
            max_order=3,
            branch_angle_mean_deg=58.0,
            branch_angle_std_deg=6.0,
            apical_dominance=0.40,
            gravitropism=-0.12,
            internode_length_base_m=0.35,
            crookedness=0.14,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.PALMATE_5,
            margin_type=MarginType.SERRATE,
            blade_length_cm=7.5,
            aspect_ratio=1.05,
            petiole_length_ratio=0.70,
            teeth_count=32,
            tooth_height_ratio=0.045,
            transverse_curl=0.18,
            longitudinal_droop=0.35,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.ACTINODROMOUS,
            vla_mm_per_mm2=8.8,
            secondary_vein_pairs=5,
            divergence_angle_deg=42.0,
            primary_radius_mm=0.75,
            secondary_radius_mm=0.25,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.64,
            youngs_modulus_gpa=10.8,
            leaf_mass_per_area_g_m2=65.0,
        )
    ),

    "acer_pseudoplatanus": BotanicalSpeciesPreset(
        scientific_name="Acer pseudoplatanus",
        common_name="Sycamore Maple",
        family="Sapindaceae",
        biome="Temperate Deciduous",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Large broadleaf canopy maple, stout trunk, leathery 5-lobed leaves with crenate-serrate margins.",
        allometry=AllometricProfile(
            dbh_min_m=0.05,
            dbh_max_m=1.50,
            dbh_default_m=0.50,
            height_a=1.98,
            height_b=0.58,
            height_max_m=35.0,
            crown_radius_c=0.52,
            crown_radius_d=0.55,
            crown_depth_ratio=0.60,
            pipe_exponent_delta=2.30,
            wood_density_g_cm3=0.63,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.RAUH,
            phyllotaxis=PhyllotaxisType.DECUSSATE,
            max_order=3,
            branch_angle_mean_deg=48.0,
            branch_angle_std_deg=5.5,
            apical_dominance=0.65,
            gravitropism=-0.16,
            internode_length_base_m=0.46,
            crookedness=0.12,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.PALMATE_5,
            margin_type=MarginType.SERRATE,
            blade_length_cm=14.0,
            aspect_ratio=1.15,
            petiole_length_ratio=0.85,
            teeth_count=40,
            tooth_height_ratio=0.035,
            transverse_curl=0.20,
            longitudinal_droop=0.38,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.ACTINODROMOUS,
            vla_mm_per_mm2=7.6,
            secondary_vein_pairs=6,
            divergence_angle_deg=46.0,
            primary_radius_mm=1.05,
            secondary_radius_mm=0.32,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.63,
            youngs_modulus_gpa=11.2,
            leaf_mass_per_area_g_m2=78.0,
        )
    ),

    "betula_pendula": BotanicalSpeciesPreset(
        scientific_name="Betula pendula",
        common_name="Silver Birch",
        family="Betulaceae",
        biome="Boreal / Temperate",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Slender pioneer tree, pendulous weeping branchlets (positive gravitropism), doubly serrate ovate leaves.",
        allometry=AllometricProfile(
            dbh_min_m=0.04,
            dbh_max_m=0.65,
            dbh_default_m=0.28,
            height_a=2.10,
            height_b=0.61,
            height_max_m=28.0,
            crown_radius_c=0.38,
            crown_radius_d=0.51,
            crown_depth_ratio=0.50,
            pipe_exponent_delta=2.35,
            wood_density_g_cm3=0.62,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.RAUH,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=3,
            branch_angle_mean_deg=42.0,
            branch_angle_std_deg=5.5,
            apical_dominance=0.70,
            gravitropism=0.25,   # Weeping branchlets
            internode_length_base_m=0.52,
            crookedness=0.10,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.OVATE,
            margin_type=MarginType.SERRATE,
            blade_length_cm=6.0,
            aspect_ratio=1.45,
            petiole_length_ratio=0.45,
            teeth_count=26,
            tooth_height_ratio=0.04,
            transverse_curl=0.20,
            longitudinal_droop=0.40,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.CRASPEDODROMOUS,
            vla_mm_per_mm2=9.6,
            secondary_vein_pairs=8,
            divergence_angle_deg=45.0,
            primary_radius_mm=0.65,
            secondary_radius_mm=0.22,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.62,
            youngs_modulus_gpa=14.0,
            leaf_mass_per_area_g_m2=72.0,
        )
    ),

    "fagus_sylvatica": BotanicalSpeciesPreset(
        scientific_name="Fagus sylvatica",
        common_name="European Beech",
        family="Fagaceae",
        biome="Temperate Broadleaf",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Troll sympodial architecture with zig-zag planar foliage sprays, high shade tolerance, smooth thin bark.",
        allometry=AllometricProfile(
            dbh_min_m=0.05,
            dbh_max_m=1.40,
            dbh_default_m=0.45,
            height_a=2.05,
            height_b=0.59,
            height_max_m=38.0,
            crown_radius_c=0.49,
            crown_radius_d=0.56,
            crown_depth_ratio=0.58,
            pipe_exponent_delta=2.25,
            wood_density_g_cm3=0.72,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.TROLL,
            phyllotaxis=PhyllotaxisType.DISTICHOUS,
            max_order=3,
            branch_angle_mean_deg=62.0,
            branch_angle_std_deg=5.0,
            apical_dominance=0.45,
            gravitropism=-0.10,
            internode_length_base_m=0.42,
            crookedness=0.12,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.ELLIPTIC,
            margin_type=MarginType.ENTIRE,
            blade_length_cm=8.5,
            aspect_ratio=1.65,
            petiole_length_ratio=0.20,
            teeth_count=0,
            transverse_curl=0.25,
            longitudinal_droop=0.28,
            undulation_amplitude=0.08,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.CRASPEDODROMOUS,
            vla_mm_per_mm2=6.8,
            secondary_vein_pairs=7,
            divergence_angle_deg=44.0,
            primary_radius_mm=0.78,
            secondary_radius_mm=0.26,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.72,
            youngs_modulus_gpa=13.2,
            leaf_mass_per_area_g_m2=82.0,
        )
    ),

    "ficus_elastica": BotanicalSpeciesPreset(
        scientific_name="Ficus elastica",
        common_name="Rubber Fig",
        family="Moraceae",
        biome="Tropical Rainforest",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Tropical rainforest tree with massive fluted Gielis buttress roots, thick leathery leaves, brochidodromous looping veins.",
        allometry=AllometricProfile(
            dbh_min_m=0.06,
            dbh_max_m=1.60,
            dbh_default_m=0.50,
            height_a=1.78,
            height_b=0.55,
            height_max_m=30.0,
            crown_radius_c=0.62,
            crown_radius_d=0.62,
            crown_depth_ratio=0.65,
            pipe_exponent_delta=2.15,
            wood_density_g_cm3=0.52,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.RAUH,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=2,
            branch_angle_mean_deg=52.0,
            branch_angle_std_deg=6.0,
            apical_dominance=0.60,
            gravitropism=-0.15,
            internode_length_base_m=0.38,
            crookedness=0.15,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.ELLIPTIC,
            margin_type=MarginType.ENTIRE,
            blade_length_cm=22.0,
            aspect_ratio=2.10,
            petiole_length_ratio=0.25,
            thickness_mm=0.45,
            transverse_curl=0.32,
            longitudinal_droop=0.22,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.BROCHIDODROMOUS,
            vla_mm_per_mm2=11.2,
            secondary_vein_pairs=18,
            divergence_angle_deg=68.0,
            primary_radius_mm=1.40,
            secondary_radius_mm=0.28,
            secondary_curvature=0.75,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.52,
            youngs_modulus_gpa=9.5,
            leaf_mass_per_area_g_m2=165.0,
        )
    ),

    "pinus_sylvestris": BotanicalSpeciesPreset(
        scientific_name="Pinus sylvestris",
        common_name="Scots Pine",
        family="Pinaceae",
        biome="Boreal / Montane Conifer",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Conifer with Massart tiering when young, flat umbrella crown in maturity, acicular needle foliage.",
        allometry=AllometricProfile(
            dbh_min_m=0.04,
            dbh_max_m=0.90,
            dbh_default_m=0.35,
            height_a=2.25,
            height_b=0.54,
            height_max_m=36.0,
            crown_radius_c=0.35,
            crown_radius_d=0.49,
            crown_depth_ratio=0.45,
            pipe_exponent_delta=2.40,
            wood_density_g_cm3=0.51,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.MASSART,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=3,
            branch_angle_mean_deg=76.0,
            branch_angle_std_deg=4.5,
            apical_dominance=0.85,
            gravitropism=-0.28,
            internode_length_base_m=0.65,
            crookedness=0.08,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.ACICULAR,
            margin_type=MarginType.ENTIRE,
            blade_length_cm=5.5,
            aspect_ratio=8.0,
            petiole_length_ratio=0.05,
            thickness_mm=0.85,
            transverse_curl=0.05,
            longitudinal_droop=0.15,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.PARALLELODROMOUS,
            vla_mm_per_mm2=2.8,
            secondary_vein_pairs=0,
            divergence_angle_deg=0.0,
            primary_radius_mm=0.45,
            secondary_radius_mm=0.0,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.51,
            youngs_modulus_gpa=12.0,
            leaf_mass_per_area_g_m2=210.0,
        )
    ),

    "sequoiadendron_giganteum": BotanicalSpeciesPreset(
        scientific_name="Sequoiadendron giganteum",
        common_name="Giant Sequoia",
        family="Cupressaceae",
        biome="Montane Sierra Nevada",
        growth_habit="Canopy Giant",
        po_growth_form="PO:0009006",
        notes="Largest living tree by volume, massive fluted Gielis m=8 buttress flare, thick fire-resistant bark, conical crown.",
        allometry=AllometricProfile(
            dbh_min_m=0.15,
            dbh_max_m=4.50,
            dbh_default_m=1.80,
            height_a=2.65,
            height_b=0.58,
            height_max_m=85.0,
            crown_radius_c=0.32,
            crown_radius_d=0.45,
            crown_depth_ratio=0.55,
            pipe_exponent_delta=2.50,
            buttress_amplitude=0.95,
            buttress_decay=8.0,
            wood_density_g_cm3=0.38,
            bark_fraction=0.16,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.MASSART,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=3,
            branch_angle_mean_deg=82.0,
            branch_angle_std_deg=4.0,
            apical_dominance=0.92,
            gravitropism=-0.35,
            internode_length_base_m=0.90,
            crookedness=0.05,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.ACICULAR,
            margin_type=MarginType.ENTIRE,
            blade_length_cm=1.2,
            aspect_ratio=4.5,
            petiole_length_ratio=0.02,
            thickness_mm=0.75,
            transverse_curl=0.05,
            longitudinal_droop=0.08,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.PARALLELODROMOUS,
            vla_mm_per_mm2=2.2,
            secondary_vein_pairs=0,
            divergence_angle_deg=0.0,
            primary_radius_mm=0.35,
            secondary_radius_mm=0.0,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.38,
            youngs_modulus_gpa=9.2,
            leaf_mass_per_area_g_m2=260.0,
        )
    ),

    "ginkgo_biloba": BotanicalSpeciesPreset(
        scientific_name="Ginkgo biloba",
        common_name="Maidenhair Tree",
        family="Ginkgoaceae",
        biome="Temperate Relict",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Ancient gymnosperm with flabellate fan-shaped leaves, dichotomous open venation, long spur shoots.",
        allometry=AllometricProfile(
            dbh_min_m=0.04,
            dbh_max_m=1.20,
            dbh_default_m=0.40,
            height_a=1.95,
            height_b=0.57,
            height_max_m=30.0,
            crown_radius_c=0.42,
            crown_radius_d=0.52,
            crown_depth_ratio=0.60,
            pipe_exponent_delta=2.30,
            wood_density_g_cm3=0.54,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.MASSART,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=2,
            branch_angle_mean_deg=48.0,
            branch_angle_std_deg=6.0,
            apical_dominance=0.75,
            gravitropism=-0.20,
            internode_length_base_m=0.45,
            crookedness=0.10,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.FLABELLATE,
            margin_type=MarginType.ENTIRE,
            blade_length_cm=6.5,
            aspect_ratio=0.95,
            petiole_length_ratio=0.90,
            transverse_curl=0.15,
            longitudinal_droop=0.28,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.FLABELLATE,
            vla_mm_per_mm2=5.2,
            secondary_vein_pairs=0,
            divergence_angle_deg=22.0,
            primary_radius_mm=0.60,
            secondary_radius_mm=0.18,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.54,
            youngs_modulus_gpa=9.8,
            leaf_mass_per_area_g_m2=110.0,
        )
    ),

    "eucalyptus_globulus": BotanicalSpeciesPreset(
        scientific_name="Eucalyptus globulus",
        common_name="Tasmanian Blue Gum",
        family="Myrtaceae",
        biome="Mediterranean / Subtropical",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Attims architecture with rapid vertical growth, falcate-lanceolate leaves, high vein density (12.4 mm/mm²).",
        allometry=AllometricProfile(
            dbh_min_m=0.05,
            dbh_max_m=1.90,
            dbh_default_m=0.60,
            height_a=2.40,
            height_b=0.63,
            height_max_m=55.0,
            crown_radius_c=0.44,
            crown_radius_d=0.50,
            crown_depth_ratio=0.48,
            pipe_exponent_delta=2.45,
            wood_density_g_cm3=0.78,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.ATTIMS,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=3,
            branch_angle_mean_deg=38.0,
            branch_angle_std_deg=6.5,
            apical_dominance=0.82,
            gravitropism=0.18,
            internode_length_base_m=0.60,
            crookedness=0.14,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.LANCEOLATE,
            margin_type=MarginType.ENTIRE,
            blade_length_cm=18.0,
            aspect_ratio=3.8,
            petiole_length_ratio=0.22,
            transverse_curl=0.15,
            longitudinal_droop=0.55,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.BROCHIDODROMOUS,
            vla_mm_per_mm2=12.4,
            secondary_vein_pairs=22,
            divergence_angle_deg=55.0,
            primary_radius_mm=1.10,
            secondary_radius_mm=0.20,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.78,
            youngs_modulus_gpa=16.5,
            leaf_mass_per_area_g_m2=185.0,
        )
    ),

    "populus_tremula": BotanicalSpeciesPreset(
        scientific_name="Populus tremula",
        common_name="Common Aspen",
        family="Salicaceae",
        biome="Temperate / Boreal",
        growth_habit="Canopy Tree",
        po_growth_form="PO:0009006",
        notes="Rapid pioneer species, flattened petiole allowing high aerodynamic flutter, orbicular leaves with crenate margins.",
        allometry=AllometricProfile(
            dbh_min_m=0.04,
            dbh_max_m=0.80,
            dbh_default_m=0.32,
            height_a=2.15,
            height_b=0.60,
            height_max_m=30.0,
            crown_radius_c=0.36,
            crown_radius_d=0.50,
            crown_depth_ratio=0.52,
            pipe_exponent_delta=2.30,
            wood_density_g_cm3=0.48,
        ),
        architecture=ArchitectureProfile(
            model=HalleOldemanModel.RAUH,
            phyllotaxis=PhyllotaxisType.SPIRAL,
            max_order=3,
            branch_angle_mean_deg=45.0,
            branch_angle_std_deg=5.0,
            apical_dominance=0.78,
            gravitropism=-0.15,
            internode_length_base_m=0.50,
            crookedness=0.10,
        ),
        leaf_morphology=LeafMorphologyProfile(
            archetype=LeafArchetype.OVATE,
            margin_type=MarginType.CRENATE,
            blade_length_cm=7.0,
            aspect_ratio=1.10,
            petiole_length_ratio=0.80,
            teeth_count=22,
            tooth_height_ratio=0.035,
            transverse_curl=0.12,
            longitudinal_droop=0.45,
        ),
        venation=VenationProfile(
            pattern=VenationPattern.CRASPEDODROMOUS,
            vla_mm_per_mm2=8.2,
            secondary_vein_pairs=7,
            divergence_angle_deg=48.0,
            primary_radius_mm=0.72,
            secondary_radius_mm=0.24,
        ),
        biomechanics=BiomechanicalProfile(
            wood_density_g_cm3=0.48,
            youngs_modulus_gpa=10.5,
            leaf_mass_per_area_g_m2=68.0,
        )
    ),
}


def get_preset_names() -> list[tuple[str, str, str]]:
    """Returns list of (id, label, description) for Blender UI enum."""
    items = []
    for key, spec in SPECIES_CATALOG.items():
        desc = f"{spec.scientific_name} ({spec.family}) - {spec.biome}"
        items.append((key, f"{spec.common_name} ({spec.scientific_name})", desc))
    return items


def get_species_preset(key: str) -> BotanicalSpeciesPreset:
    """Retrieves a botanical preset by ID, falling back to English Oak."""
    return SPECIES_CATALOG.get(key, SPECIES_CATALOG["quercus_robur"])
